In [121]:
# Importing the necessary libraries
import numpy as np
import pandas as pd

In [122]:
# Loading the dataset
data = pd.read_csv('winequality/winequality-red.csv', sep=";")

In [123]:
# Checking the top rows of data
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [124]:
# Checking of null values
data.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

There are 11 input variables and all of them continous variables. There are no missing values

In [125]:
X = data.iloc[:, :-1]

In [126]:
X.iloc[:, 1].max()

1.58

In [127]:
for col in X.columns:
    X[col] = (X[col] - X[col].min()) / (X[col].max() - X[col].min())

In [128]:
y = data.quality.values

In [129]:
X['bias'] = 1

In [130]:
X.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0       0.247788          0.397260         0.00        0.068493   0.106845   
1       0.283186          0.520548         0.00        0.116438   0.143573   
2       0.283186          0.438356         0.04        0.095890   0.133556   
3       0.584071          0.109589         0.56        0.068493   0.105175   
4       0.247788          0.397260         0.00        0.068493   0.106845   

   free sulfur dioxide  total sulfur dioxide   density        pH  sulphates  \
0             0.140845              0.098940  0.567548  0.606299   0.137725   
1             0.338028              0.215548  0.494126  0.362205   0.209581   
2             0.197183              0.169611  0.508811  0.409449   0.191617   
3             0.225352              0.190813  0.582232  0.330709   0.149701   
4             0.140845              0.098940  0.567548  0.606299   0.137725   

    alcohol  bias  
0  0.153846     1  
1  0.215385     1  
2  0.215385     1  
3  0.215385     1  
4  0.153846     1

In [131]:
weights = np.zeros((X.shape[1], 1))

In [132]:
weights.shape

(12, 1)

In [133]:
output = np.dot(X, weights)

In [134]:
output

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [135]:
y = data.quality.values

In [136]:
y = y.reshape(-1, 1)

In [137]:
learning_rate = 1e-3
n_epochs = 100

In [138]:
def mse(y, yhat):
    return np.mean((y - yhat) ** 2)

In [139]:
weights

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [140]:
m = len(X)

In [141]:
X.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0       0.247788          0.397260         0.00        0.068493   0.106845   
1       0.283186          0.520548         0.00        0.116438   0.143573   
2       0.283186          0.438356         0.04        0.095890   0.133556   
3       0.584071          0.109589         0.56        0.068493   0.105175   
4       0.247788          0.397260         0.00        0.068493   0.106845   

   free sulfur dioxide  total sulfur dioxide   density        pH  sulphates  \
0             0.140845              0.098940  0.567548  0.606299   0.137725   
1             0.338028              0.215548  0.494126  0.362205   0.209581   
2             0.197183              0.169611  0.508811  0.409449   0.191617   
3             0.225352              0.190813  0.582232  0.330709   0.149701   
4             0.140845              0.098940  0.567548  0.606299   0.137725   

    alcohol  bias  
0  0.153846     1  
1  0.215385     1  
2  0.215385     1  
3  0.215385     1  
4  0.153846     1

In [142]:
y

array([[5],
       [5],
       [5],
       ...,
       [6],
       [5],
       [6]])

In [143]:
predictions

[array([[-29528766.75413322]]),
 array([[-29627916.96715545]]),
 array([[-29215993.92115697]]),
 array([[-31074604.97459542]]),
 array([[-29757818.84244366]]),
 array([[-29825924.3143723]]),
 array([[-28184084.00732761]]),
 array([[-27630081.09313677]]),
 array([[-28306891.48480077]]),
 array([[-32599866.27484083]]),
 array([[-27663175.52096512]]),
 array([[-32725587.98857874]]),
 array([[-28522772.92200325]]),
 array([[-31120516.11075266]]),
 array([[-33724412.71009512]]),
 array([[-33976174.65339527]]),
 array([[-33183212.62234637]]),
 array([[-31186456.7509267]]),
 array([[-29151610.08692335]]),
 array([[-30533537.76367944]]),
 array([[-31540105.28375445]]),
 array([[-32799336.59491099]]),
 array([[-29077515.48765023]]),
 array([[-28678596.03821916]]),
 array([[-30328019.86483975]]),
 array([[-27624979.70592029]]),
 array([[-28441173.84857231]]),
 array([[-29317722.87177021]]),
 array([[-30604991.9868483]]),
 array([[-29715612.77364758]]),
 array([[-30414260.47756635]]),
 array([[-3

In [145]:
for epoch in range(30):
    predictions = []
    for i in range(len(X)):
        
        x = np.array(X.iloc[i].values).reshape(1, 12)
        
        yhat = np.dot(x, weights)
        error = y[i].reshape(1, 1) - yhat
        dw = x * error[0][0]
        weights[:-1] += learning_rate * dw.reshape(12, 1)[:-1]
        weights[-1] += (learning_rate * error)[0][0]
        predictions.append(yhat)
    print(mse(y, predictions))

0.7854967701937737
0.7837666012028545
0.7830992979452853
0.7833194173833067
0.7842689987818385
0.7858123116999347
0.7878331325218657
0.7902321338391827
0.7929246141991252
0.7958385300782821
0.7989127890539228
0.802095768721794
0.8053440309237061
0.8086212051228996
0.81189701840764
0.8151464527123518
0.818349012503317
0.8214880884517075
0.8245504045684393
0.8275255379517772
0.8304055017406764
0.8331843831091514
0.8358580292086413
0.8384237748909859
0.8408802068453255
0.8432269594754662
0.8454645384453261
0.8475941683417303
0.8496176613569469
0.851537304287516


In [119]:
X.iloc[0]

fixed acidity           0.247788
volatile acidity        0.397260
citric acid             0.000000
residual sugar          0.068493
chlorides               0.106845
free sulfur dioxide     0.140845
total sulfur dioxide    0.098940
density                 0.567548
pH                      0.606299
sulphates               0.137725
alcohol                 0.153846
bias                    1.000000
Name: 0, dtype: float64

In [86]:
y[0].reshape(1, 1) - yhat

array([[1322369.90913878]])

In [88]:
np.dot(X.iloc[0], weights.T) - y[0]

ValueError: shapes (12,) and (1,12) not aligned: 12 (dim 0) != 1 (dim 0)

In [118]:
for epoch in range(30):
    yhat = np.dot(X, weights.T)
    error = y - yhat
    dw = np.dot(error.T, X.iloc[:, :-1])
    weights[:-1] -= learning_rate * dw
    weights[-1] -= learning_rate * error.sum()
    print("Error: ", mse(y, yhat))

ValueError: shapes (1599,12) and (1,12) not aligned: 12 (dim 1) != 1 (dim 0)

In [ ]:
dw = np.dot((y - output).T, X)

In [ ]:
weights - dw

In [ ]:
dw.shape

In [33]:
from sklearn.linear_model import LinearRegression

In [34]:
l = LinearRegression()

In [35]:
l.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [37]:
from sklearn.metrics import r2_score

In [38]:
r2_score(y, l.predict(X))

0.36055170303868833

In [147]:
X.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0       0.247788          0.397260         0.00        0.068493   0.106845   
1       0.283186          0.520548         0.00        0.116438   0.143573   
2       0.283186          0.438356         0.04        0.095890   0.133556   
3       0.584071          0.109589         0.56        0.068493   0.105175   
4       0.247788          0.397260         0.00        0.068493   0.106845   

   free sulfur dioxide  total sulfur dioxide   density        pH  sulphates  \
0             0.140845              0.098940  0.567548  0.606299   0.137725   
1             0.338028              0.215548  0.494126  0.362205   0.209581   
2             0.197183              0.169611  0.508811  0.409449   0.191617   
3             0.225352              0.190813  0.582232  0.330709   0.149701   
4             0.140845              0.098940  0.567548  0.606299   0.137725   

    alcohol  bias  
0  0.153846     1  
1  0.215385     1  
2  0.215385     1  
3  0.215385     1  
4  0.153846     1

In [153]:
y = np.array(data.quality.values).reshape(1599, 1)

In [154]:
weights = np.zeros((X.shape[1], 1))

In [163]:
from sklearn.metrics import r2_score

In [188]:
rss = ((y - yhat).reshape(1599,) ** 2).sum()

In [189]:
tss = ((y - y.mean()).reshape(1599,) ** 2).sum()

In [191]:
r2 = 1 - rss / tss

In [192]:
r2

-0.21357764683530744

In [167]:
for epoch in range(n_epochs):
    yhat = np.dot(X, weights)
    yhat = yhat.reshape(1599, 1)
    error = yhat - y
    dw = np.dot(error.T, X.iloc[:, :-1])
    weights[:-1] -= learning_rate * dw.T / m
    weights[-1] -= learning_rate * error.mean()
    print(r2_score(y, yhat))

-0.21462556497246554
-0.214614176891337
-0.21460280730097803
-0.2145914561302178
-0.21458012330816323
-0.2145688087641937
-0.21455751242796395
-0.21454623422940022
-0.21453497409870081
-0.21452373196633445
-0.2145125077630392
-0.2145013014198216
-0.21449011286795572
-0.21447894203898143
-0.21446778886470375
-0.214456653277193
-0.2144455352087824
-0.21443443459206635
-0.21442335135990165
-0.21441228544540425
-0.21440123678195078
-0.21439020530317432
-0.21437919094296576
-0.2143681936354731
-0.21435721331509838
-0.21434624991649787
-0.21433530337458118
-0.21432437362451084
-0.21431346060169987
-0.21430256424181215
-0.21429168448075964
-0.21428082125470427
-0.21426997450005425
-0.21425914415346403
-0.21424833015183498
-0.21423753243231158
-0.21422675093228172
-0.21421598558937727
-0.21420523634147104
-0.2141945031266761
-0.21418378588334552
-0.214173084550072
-0.21416239906568557
-0.2141517293692532
-0.21414107540007832
-0.21413043709769952
-0.21411981440188943
-0.21410920725265403
-0.214

In [160]:
(y - yhat).shape

(1599, 1)

In [161]:
dw.shape

(1, 11)

In [ ]:
wei